src/functions/LogoutFunction.js, src/routes/AppRouter.js
LogoutFunction.js파일을 추가 함으로서 로그아웃 기능을 구현하고, 이를 AppRouter.js파일에 적용하였다.
close #15
=> feat: 로그아웃 기능 구현 및 적용

src/functions/NoticeFunction.js, src/pages/NoticeListPage.js, src/pages/NoticeViewPage.js
데이터 전달해주는 방식을 link 안에서 state로 넘겨주는 방식으로 변경함
(#20)
=> refactor/#20 (NoticeListView 에서 데이터 전달해주는 방식 변경)

src/functions/DeleteAccountFunction.js, src/functions/UpdatePasswd.js
=> refactor: 파일 및 함수 이름 수정

src/functions/NoticeFunction.js, src/pages/AdminNoticeWritePage.js, src/pages/NoticeListPage.js
=> feat: 공지사항 작성 구현

src/App.js, src/functions/UserFunction.js, src/repositories/UserRepository.js
App.js에 있는 userObject에 userModel 데이터를 읽어서 저장해두었음
close #19
=> feat: auth state에 따라 user 정보 읽기

src/functions/NoticeFunction.js, src/pages/NoticeListPage.js, src/pages/NoticeViewPage.js, src/repositories/NoticeRepository.js
공지사항 리스트를  NoticeModel을 사용하여 구현
(#35)
=> refactor: 공지사항 리스트 구현 방식 변경

src/pages/AdminNoticeUpdatePage.js, src/pages/NoticeListPage.js, src/pages/NoticeViewPage.js
=> feat: update page에 수정할것 불러오기

src/functions/NoticeFunction.js, src/pages/AdminNoticeUpdatePage.js, src/pages/AdminNoticeWritePage.js, src/repositories/NoticeRepository.js
파베에서 데이터 불러와서 수정페이지에 띄우고 공지사항 수정까지 되는것 확인함
=> feat: 공지사항 수정기능 구현

src/functions/NoticeFunction.js, src/pages/NoticeViewPage.js, src/repositories/NoticeRepository.js
개별 공지사항에서 삭제하기 버튼을 눌렀을 때 공지 삭제 하는 기능 구현
(#45)
=> feat: 공지사항 삭제 기능 구현

src/functions/NoticeFunction.js, src/pages/AdminNoticeUpdatePage.js, src/pages/AdminNoticeWritePage.js, src/pages/NoticeViewPage.js
삭제 후 리스트로 이동, 추가 후 추가된 공지글로 이동, 수정 후 수정된 공지글로 이동
(#47)
=> feat: 공지사항 기능 사이에 리다이렉션 추가

src/pages/AdminNoticeWritePage.js, src/pages/NoticeListPage.js
가장 최신 공지사항의 아이디를 가져와서 그 공지글 아이디에 1을 증가
(#49)
=> feat: 공지사항 아이디 하나씩 증가하는 방식으로 구현

src/functions/NoticeFunction.js, src/pages/AdminNoticeUpdatePage.js
공지사항 업로드 시 발생한 에러를 함수를 수정함으로 해결
(#57)
=> fix: 공지사항 업데이트 시 발생한 에러 해결

src/functions/NoticeFunction.js
NoticeFunction안에 있는 onAdminWriteNewNoticeSubmit 함수 수정
(#57)
=> feat: 공지사항 작성할 때 파일 업로 드 시 문제점 해결

src/pages/NoticeViewPage.js
=> feat: 공지사항 글에 첨부파일 추가

src/pages/NoticeListPage.js, src/styles/NoticeListStyle.scss, src/widgets/NoticePagination.js
=> feat: 공지사항 list css 구현

src/pages/AdminNoticeWritePage.js, src/pages/NoticeListPage.js, src/pages/NoticeViewPage.js, src/styles/AdminNoticeWriteStyle.scss, src/styles/NoticeListStyle.scss
=> feat: 공지사항 작성 page scss구현

src/pages/AdminNoticeWritePage.js, src/styles/AdminNoticeWriteStyle.scss, src/styles/NoticeListStyle.scss
=> fix: 공지사항 작성 page 수정

src/pages/NoticeListPage.js, src/pages/NoticeViewPage.js
공지사항 리스트에서 공지 이름에 걸어둔 링크를 전체 div로 변경 후 navigate
(#83)
=> refactor: 공지사항 리스트에서 개별로 이동하는 방식 수정

src/pages/AdminNoticeWritePage.js
=> fix: file 버튼 수정

src/pages/AdminNoticeUpdatePage.js
공지사항 수정 시 파일 업로드를 가능 할 수 있게 수정
(#83)
=> refactor: 공지사항 수정 시 파일 업로드 버튼 만들기

src/pages/AdminNoticeUpdatePage.js, src/pages/AdminNoticeWritePage.js, src/styles/AdminNoticeUpdateStyle.scss
=> feat: 공지사항 수정페이지 scss 구현

src/styles/NoticeViewStyle.scss
=> feat: 관리자 권한으로 보는 개별 공지사항 페이지 버튼 간격 수정

src/pages/NoticeListPage.js, src/pages/NoticeViewPage.js
공지사항 삭제 후 refresh가 안되던 문제 해결
(#98)
=> refactor: 공지사항 삭제 후 리프레시 적용

src/pages/AdminNoticeWritePage.js, src/pages/NoticeViewPage.js, src/styles/AdminNoticeUpdateStyle.scss
=> fix: 글 작성시 개행오류 수정완료

src/functions/NoticeFunction.js, src/models/NoticeModel.js, src/pages/AdminNoticeUpdatePage.js, src/pages/AdminNoticeWritePage.js, src/pages/NoticeViewPage.js, src/repositories/NoticeRepository.js
공지사항 수정할 때 수정된 첨부파일 이름 불러오도록 파베 변경
(#101)
=> feat: 공지사항 수정할 때 첨부파일 추가시, 첨부파일 이름 추가 되도록 변경

src/pages/UpdatePasswordPage.js, src/styles/UpdatePasswordStyle.scss
=> fix: 태그 오류 수정

src/styles/NoticeListStyle.scss
=> refactor: 공지사항 작성버튼 위치수정

src/styles/LogInStyle.scss, src/styles/SignInStyle.scss, src/styles/UpdatePasswordStyle.scss
버튼에 대한 마우스 이동시 커서 모양 변경 반영
(#121)
=> fix: 마우스 커서 변경

src/styles/NoticeViewStyle.scss
공지사항 수정페이지에 맞춰서 마진과 패딩 변경
(#111)
=> refactor: 공지사항 개별 페이지에 인터렉티브 적용

src/styles/NoticeViewStyle.scss
=> fix: NoticeViewStyle 오류 수정

src/styles/NoticeViewStyle.scss
=> refactor: 삭제시 커서 추가

src/pages/HeaderPage.js, src/pages/OrderCategoryPage.js, src/pages/OrderPage.js, src/routes/AppRouter.js, src/routes/RouteName.js
=> feat: 페이지 네비게이션 정리

src/pages/OrderPage.js
=> feat: 주문상세 페이지 구현

src/models/OrderModel.js
주문예약과 주문 내역확인을 위한 Order 모델 생성
(#143)
=> feat: Order 모델과 컨버터 생성

src/models/OrderModel.js
추후 확장을 생각하여 총액과 완성될 시간을 저장할 필드를 추가, 그리고 타입을 적어줌
(#143)
=> feat: Order 모델에 필드 추가

src/pages/AdminNoticeUpdatePage.js, src/pages/AdminNoticeWritePage.js, src/pages/NoticeViewPage.js
공지사항 작성과 수정 시 발생한 오류 수정, 그리고 네비게이션 수정
(#150)
=> fix: 공지사항 페이지 오류 수정 & 네비게이션 수정

src/pages/OrderCategoryPage.js, src/styles/NoticeListStyle.scss, src/styles/OrderCategoryStyle.scss
=> feat: 주문하기 카테고리 박스완성

src/models/MyOrderModel.js
User document에 넣을 주문ref document model
close #143
=> feat/#143 (Order 모델과 MyOrder 모델 작성)

src/pages/OrderCategoryPage.js, src/styles/NoticeListStyle.scss, src/styles/OrderCategoryStyle.scss
=> refactor: 주문예약페이지 css 수정

src/pages/OrderCategoryPage.js, src/styles/OrderCategoryStyle.scss
=> feat: 주문예약페이지 카드 flip 애니메이션 추가

src/pages/NoticeViewPage.js
첨부파일이 만약 이미지 일 경우, 이미지 보여주기 구현
(#164)
=> feat: 공지사항 개별페이지에 이미지 보여주는 것 구현

src/pages/OrderCategoryPage.js, src/pages/OrderPage.js, src/styles/AdminNoticeUpdateStyle.scss, src/styles/OrderStyle.scss
=> feat: 전 날 까지 한 것

src/functions/OrderFunction.js, src/pages/AdminNoticeWritePage.js, src/pages/OrderPage.js, src/repositories/OrderRepository.js
=> feat: order function정리

src/functions/OrderFunction.js, src/pages/OrderCategoryPage.js, src/pages/OrderPage.js, src/repositories/OrderRepository.js
=> feat: 파베 데이터 추가 (제목만) 완료

src/pages/OrderPage.js
=> feat: 주문상세페이지 기능 및 디자인 적용

src/pages/OrderCategoryPage.js, src/styles/NoticeListStyle.scss
=> refactor: 공지사항 리스트 스크롤바 수정

src/functions/NoticeFunction.js, src/pages/AdminNoticeUpdatePage.js
공지사항 작성시 첨부파일 올릴때 attachment가 https url 이도록 수정, 또한 공지사항 수정 시 파일 업로드하는 법 수정 & 만약 파일이 바뀌지 않앗다면 수정하지 않게 구현
(#170)
=> feat: 공지사항에 첨부파일 올리는 방식 변경

src/pages/OrderConfirmListPage.js, src/styles/OrderConfirmListStyle.scss
=> feat/#177 (OrderCofirmListPage 디자인 구현 중

src/pages/OrderPage.js
=> feat: 주문상세 디자인

src/pages/OrderPage.js, src/styles/OrderStyle.scss
=> feat: 각 카테고리별 상세화

src/functions/OrderFunction.js, src/pages/OrderPage.js, src/styles/OrderStyle.scss
=> feat: 정보 파베에 들어가는 것 확인

src/pages/OrderPage.js
=> feat: 셀렉옵션 [-----]추가

src/pages/OrderPage.js, src/styles/OrderStyle.scss
=> feat: 파일 화면 디자인

src/pages/NoticeListPage.js
=> fix: 공지사항 페이지 줄 넘김 오류 해결

src/styles/NoticeListStyle.scss, src/styles/NoticeViewStyle.scss
=> fix: 공지사항 페이지 style 수정

src/functions/OrderFunction.js, src/pages/OrderPage.js
=> feat: 주문상세 페이지 파일 미리보기

src/styles/NoticeListStyle.scss, src/styles/OrderStyle.scss
=> fix: 공지사항 list 페이지 수정

src/functions/OrderFunction.js, src/pages/OrderPage.js
파일 업로드 취소 구현을 위한 코드 추가 및 삭제
(#140)
=> feat: 파일 업로드 취소 구현

src/pages/OrderPage.js
=> fix: 주문페이지 고치기

src/functions/OrderFunction.js, src/pages/OrderPage.js
=> feat: 이미지 파일 업로드

src/functions/OrderFunction.js, src/pages/OrderPage.js
변수명을 명확하게 변경 => imageUrlUrl, setImageUrl
(#140)
=> feat: 변수명 변경

src/pages/OrderPage.js
파일 업로드 시도 상황시에 첨부파일이 없을 시 주문 버튼 비활성화 반영
(#140)
=> feat: 파일 업로드 예외처리

src/functions/OrderFunction.js, src/models/OrderModel.js, src/repositories/OrderRepository.js
=> feat: Order 모델 수정

src/pages/NoticeListPage.js, src/pages/NoticeViewPage.js
noticeData = location.state.data 를 location.state 로 수정
(#210)
=> fix: 공지사항 개별 페이지로 바로 넘어갈 때 생긴 에러 수정

src/pages/OrderPage.js
기타 주문사항 페이지는 다른 페이지와 구별
(#140)
=> feat: 기타 주문사항 페이지 수정

src/functions/OrderConfirmFunction.js, src/models/OrderModel.js
string type이었던 uid를 reference type인 userDocRef로 변경하면서 발생하였던 오류 해결
(#207)
=> feat/#207 (Order 모델에 uid를 userDocRef로 변경)

package-lock.json, package.json, src/pages/NoticeListPage.js, src/styles/NoticeListStyle.scss
=> refactor: 공지사항 list 페이지네이션 수정

src/functions/OrderConfirmFunction.js, src/functions/OrderFunction.js, src/functions/UserFunction.js, src/repositories/OrderRepository.js
주문 예약 시 , 해당 유저의 정보에 주문 예약한 정보 저장
(#207)
=> feat: 주문 예약 할 때 user 컬렉션 안에 myOrders 하위 컬렉션 추가

src/functions/OrderConfirmFunction.js, src/pages/OrderConfirmListPage.js
userEffect 안에서 관리자와 사용자에 대해서 리스트 불러오는 방식 변경
(#217)
=> feat: 관리자와 사용자의 주문 예약 확인 order list 불러오는 방식 변경

src/pages/NoticeListPage.js, src/styles/NoticeListStyle.scss
=> fix: 공지사항 잘리는 부분 수정

src/pages/NoticeListPage.js, src/styles/NoticeListStyle.scss, src/widgets/NoticePagination.js
=> refactor: 공지사항 리스트 페이지네이션 원래대로 수정

src/pages/OrderPage.js, src/styles/NoticeListStyle.scss, src/styles/OrderStyle.scss
=> refactor: 주문상세 페이지 헤더고정, 스크롤바 수정

src/pages/OrderPage.js, src/styles/OrderStyle.scss
=> refactor: 상세보기 border조정

src/functions/OrderFunction.js, src/pages/OrderPage.js
=> refactor: 오타수정

src/pages/OrderPage.js, src/styles/OrderStyle.scss
=> fix: 파일 업로드 오류 해결

src/assets/OrderFileCancelAsset.svg, src/pages/OrderPage.js, src/styles/OrderStyle.scss
=> fix: 파일선택 scss 추가

src/styles/OrderStyle.scss
=> refactor: scss비율화

src/functions/OrderFunction.js, src/pages/OrderPage.js, src/styles/OrderStyle.scss
=> feat: 주문확인 팝업 추가

src/pages/HeaderPage.js, src/pages/PaperInfoPage.js, src/routes/AppRouter.js, src/routes/RouteName.js, src/styles/PaperInfoStyle.scss
=> feat: 종이정보 페이지 라우터 추가

src/pages/OrderPage.js, src/styles/OrderStyle.scss
=> feat: 기타 주문사항 페이지 css

src/pages/HeaderPage.js, src/styles/HeaderStyle.scss
=> feat: 수정된 팝업 디자인 구현

src/functions/OrderFunction.js, src/pages/OrderPage.js, src/styles/OrderStyle.scss
=> feat: 주문상세 페이지 수정

src/pages/NoticeAllPage.js, src/pages/NoticeListPage.js, src/routes/AppRouter.js, src/routes/RouteName.js, src/styles/NoticeAllStyle.scss, src/styles/NoticeListStyle.scss
=> feat: 모든 공지사항 페이지 라우팅

src/pages/HeaderPage.js, src/pages/UserLeavePage.js, src/routes/AppRouter.js, src/routes/RouteName.js, src/styles/HeaderStyle.scss
my profile 팝업창에서 회원탈퇴버튼에 페이지 이동 기능 추가
(#229)
=> feat/#229 (회원탈퇴 페이지 이동기능 추가)

src/pages/OrderConfirmViewPage.js, src/styles/OrderConfirmViewStyle.scss
유저 이름과 번호 추가,  첨부파일 이름 스타일 화 그리고 나머지 데이터 스크롤 가능하게 수정
(#161)
=> feat: 주문 상세 확인 페이지 디자인 수정, 돌아가기 버튼 추가

src/pages/NoticeAllPage.js, src/pages/NoticeListPage.js, src/routes/AppRouter.js, src/styles/NoticeAllStyle.scss, src/styles/NoticeListStyle.scss
=> feat: 공지사항 전체 리스트에서 데이터 불러오기

src/pages/NoticeAllPage.js, src/pages/OrderConfirmListPage.js, src/routes/RouteName.js, src/styles/NoticeAllStyle.scss
=> feat: 공지사항 검색기능 추가

package-lock.json, package.json, src/pages/OrderPage.js, src/styles/OrderStyle.scss
옵션을 선택하지 않아도 기본 값을 전달 할 수 있도록 수정
(140)
=> feat: 옵션 기본값 설정

src/pages/HeaderPage.js, src/styles/HeaderStyle.scss
=> feat: 헤더 css 추가

src/functions/NoticeFunction.js, src/pages/NoticeAllPage.js, src/pages/NoticeListPage.js
공지사항 검색 할 때 엔터 입력 없이 실시간으로 검색 해서 해당 검색어를 가진 공지사항이 나오게 수정
(#260)
=> refactor: 공지사항 검색 시 엔터 입력 없이도 실시간으로 검색 가능하게 수정

src/pages/OrderPage.js, src/styles/OrderStyle.scss
=> feat: 주문 상세페이지 수정

src/pages/HeaderPage.js, src/pages/NoticeListPage.js, src/styles/NoticeListStyle.scss
=> feat: header수정

src/pages/NoticeAllPage.js, src/styles/NoticeAllStyle.scss
사님이 중요하다고 생각하는 공지 핀 할 수 있게 핀 체크 박스 추가
(#267)
=> feat: 공지사항 핀 버튼 추가

src/pages/NoticeListPage.js, src/styles/HomeStyle.scss, src/styles/NoticeListStyle.scss
=> feat: 공지사항 제목 overflow "..."처리

src/styles/NoticeListStyle.scss
=> refactor: css 픽셀 퍼센트화

src/App.js, src/ScrollToTop.js
=> feat: 페이지 스크롤 업

src/styles/OrderConfirmViewStyle.scss
=> feat: 주문개별확인에서 파일에 마우스 커서

src/pages/NoticeListPage.js, src/pages/OrderCategoryPage.js, src/styles/OrderCategoryStyle.scss
=> refactor: flip에서 hover로 변경

src/styles/PopUpWithOneButtonsWidgets.scss, src/styles/ThemeStyles.scss, src/widgets/PopUpWithOneButtonWidgets.js
=> feat: 버튼이 하나만 있는 팝업창 추가

src/styles/OrderStyle.scss
=> refactor: 주문페이지 css 수정

src/styles/OrderStyle.scss
=> refactor: 드래그 드롭 존 수정

src/pages/HeaderPage.js, src/styles/OrderStyle.scss
=> refactor: 드래그 드롭존 사이즈 수정

src/functions/UserFunction.js, src/pages/UserLeavePage.js, src/routes/AppRouter.js
주문 예약을 하는 중에 회원 탈퇴를 시도할 때 회원 탈퇴가 불가능 하다는 팝업 띄우기
(#299)
=> feat: 주문예약 중인 상태에서 회원탈퇴 불가능하게 구현

src/pages/OrderPage.js, src/styles/OrderStyle.scss
주문불가 상황시에도 주문 접수를 알리는 팝업창 뜨는 상황 오류 해결
(#140)
=> feat: 주문 버튼 버그 수정

src/pages/HomePage.js, src/pages/NoticeListPage.js, src/styles/HomeStyle.scss, src/styles/NoticeListStyle.scss, src/styles/ThemeStyles.scss
=> refactor: 픽셀값 수정

src/pages/OrderConfirmViewPage.js, src/styles/OrderConfirmViewStyle.scss, src/styles/OrderStyle.scss
주문 상세페이지의 불필요한 스크롤바 및 디스플레이 크기와 위치 조정
(#311)
=> fix: 주문 상세페이지 pdf뷰어 수정

src/functions/UserFunction.js, src/repositories/UserRepository.js
유저 컬렉션 안에 하위 컬렉션으로 있는 myOrders 데이터도 탈퇴와 함께 삭제
(#315)
=> feat: 회원 탈퇴 시 myOrders 에 있는 정보도 함께 삭제

src/pages/OrderConfirmViewPage.js, src/pages/OrderPage.js, src/styles/OrderConfirmViewStyle.scss, src/styles/OrderStyle.scss
주문 상세 및 확인 페이지에서의 pdf 페이지 확인 위젯 추가 및 코드 수정
(#321)
=> feat: 파일 페이지 확인 위젯 추가

package-lock.json, package.json, src/pages/NoticeAllPage.js, src/pages/NoticeViewPage.js, src/styles/NoticeAllStyle.scss
=> refactor: 공지사항 css 수정

src/styles/HomeStyle.scss, src/styles/NoticeAllStyle.scss
=> refactor: 배경수정

src/functions/UserFunction.js, src/pages/UserLeavePage.js, src/repositories/UserRepository.js, src/routes/AppRouter.js, src/styles/PopUpWithOneButtonsWidgets.scss, src/styles/PopUpWithTwoButtonsWidgets.scss
회원 탈퇴 시 나와야 하는 팝업창 수정, 팝업 위젯에 \n 이 적용될 수 있게  추가, 탈퇴 시 로그아웃 후 탈퇴되었다는 메시지가 나오게 라우트 추가
=> feat/#319 (회원 탈퇴에 대한 팝업 모두 생성 및 수정)

package-lock.json, package.json
주문상세 페이지 및 주문확인페이지에서의 현재 페이지 위젯 구현을 위한 설치 파일 수정
(#325)
=> feat: 현재 페이지 구현을 위한 설치 파일

src/pages/NoticeAllPage.js, src/pages/NoticeViewPage.js, src/pages/OrderPage.js, src/styles/NoticeAllStyle.scss
=> refactor: 핀 위치 수정

src/styles/NoticeAllStyle.scss
=> refactor: css수정

src/styles/AdminNoticeUpdateStyle.scss, src/styles/AdminNoticeWriteStyle.scss, src/styles/NoticeAllStyle.scss, src/styles/NoticeListStyle.scss, src/styles/NoticeViewStyle.scss, src/styles/OrderCategoryStyle.scss, src/styles/OrderConfirmListStyle.scss, src/styles/PaperInfoStyle.scss, src/styles/PopUpPaperInfoStyle.scss, src/styles/PopUpWithGifWidgets.scss, src/styles/PopUpWithOneButtonsWidgets.scss, src/styles/PopUpWithTwoButtonsWidgets.scss, src/styles/ThemeStyles.scss, src/styles/UserLeaveStyle.scss
=> refactor: theme파일 컬러함수 추가

src/styles/LogInStyle.scss, src/styles/NoticeListStyle.scss, src/styles/OrderStyle.scss, src/styles/ThemeStyles.scss
=> refactor: css 수정

src/styles/SignInStyle.scss
=> refactor: theme파일 없는 컬러 수정

src/assets/icons/MyProfileEditSaveIconAsset.svg, src/functions/UserFunction.js, src/pages/HeaderPage.js, src/repositories/UserRepository.js, src/styles/HeaderStyle.scss
유저의 정보가 수정될 때 파이어베이스에 업로드하여 정보 수정, 수정된 정보도 암호화하여 저장, 유저 repository에 새로운 파이어베이스용 함수 추가, 사용자가 정보를 수정하다 멈추어 다른 곳을 클릭 시 데이터 저장 안되게 구현, 정보가 수정되면 리로드 하여 새로운 정보를 가져오게 구현
(#335)
=> feat: 헤더에서 유저 정보 수정하는 것 구현, 사용자 이름과 휴대전화번호 바꿀 수있게 구현

src/styles/NoticeAllStyle.scss
배경, 타이틀 등 desktop, tablet, moblie버전화
=> refactor: 공지사항 페이지 반응형

src/styles/NoticeAllStyle.scss, src/styles/OrderCategoryStyle.scss, src/styles/PaperInfoStyle.scss
=> refactor: 주문카테고리 반응형

src/pages/HomePage.js, src/styles/HeaderStyle.scss, src/styles/HomeStyle.scss, src/styles/NoticeListStyle.scss, src/styles/OrderCategoryStyle.scss
=> refactor: 홈페이지 css변경

src/pages/OrderPage.js, src/styles/PopUpPaperInfoStyle.scss
=> feat: 주문 상세 페이지의 종이 정보 팝업 페이지

src/pages/HomePage.js, src/styles/HomeStyle.scss, src/styles/NoticeAllStyle.scss, src/styles/NoticeListStyle.scss, src/styles/PopUpAgreeInfoWidget.scss
=> feat: 푸터 클릭시 팝업

src/pages/HomePage.js, src/styles/NoticeListStyle.scss, src/styles/PopUpAgreeInfoWidget.scss
푸터 이용약관 클릭했을 때 노티스페이지만 blur안되었던 것 수정
=> fix: 노티스페이지 blur처리 수정

src/pages/OrderPage.js, src/styles/OrderStyle.scss, src/widgets/PopUpPaperInfo.js
=> feat: 종이 정보 팝업 함수화

src/functions/OrderConfirmFunction.js, src/pages/OrderConfirmListPage.js, src/pages/OrderConfirmViewPage.js, src/pages/OrderPage.js, src/styles/OrderConfirmViewStyle.scss
0 1 등 숫자로 저장된 항목을 글로 변경, scss 수정
(#362)
=> refactor: 주문확인 개별페이지 넣은 항목 자세하게 보이게 수정

src/pages/OrderConfirmViewPage.js, src/pages/OrderPage.js, src/styles/OrderConfirmViewStyle.scss, src/styles/OrderStyle.scss, src/styles/PopUpPaperInfoStyle.scss, src/widgets/PopUpPaperInfo.js
스테이징한 모든 파일들에 대해서 디자인적 결함 보수
(#366)
=> fix: css오류 및 결함 보수

src/pages/HeaderPage.js
로그인로그인 / 로그아웃에 따른 마이프로필 아이콘 표시
(#371)
=> fix: 조건에 따른 마이프로필 아이콘 표시

src/pages/HeaderPage.js
로그인 여부에 따른 마이프로필 버튼 위치가 잘못되어 수정
(#371)
=> fix: 마이프로필 버튼 위치 조정

src/styles/OrderStyle.scss
주문페이지에서의 입력되어진 글자에 대한 폰트 적용
(#371)
=> text입력에 대한 폰트 적용

src/styles/PopUpAgreeInfoWidget.scss
사용자에게 보이지 않게 하되, 기능은 유지하도록 구현
(feat/#377)
=> feat: 개인정보처리방침 및 이용약관 스크룰바 디자인 수정

src/styles/PopUpPaperInfoStyle.scss, src/widgets/PopUpPaperInfo.js
주문상세페이지 에서의 종이정보팝업 픽셀 조정
(#380)
=> fix: 종이정보팝업 픽셀 조정

src/routes/AppRouter.js
강제적으로 라우팅 되게 하는 조건 삭제
close #314
=> fix: Home 페이지로 강제 라우팅 문제 해결

src/pages/HomePage.js, src/styles/OrderCategoryStyle.scss, src/styles/OrderStyle.scss
=> refactor: 홈페이지 푸터

src/assets/FooterPolicyAsset.svg, src/pages/HomePage.js, src/styles/HomeStyle.scss
맞지 않은 수치 수정, 필요 없는 에셋 삭제
close #354
=> feat: footer css 수정

src/pages/HomePage.js, src/styles/PopUpAgreeInfoWidget.scss
데스크톱 사이즈마다 내려가는게 다름. 아직 계속 수정중
=> refactor: 홈에서 공지사항 내려가는 위치 수정

src/pages/HomePage.js
=> refactor: 홈페이지 버튼클릭시 부드럽게 내려가게 구현

src/pages/OrderConfirmListPage.js, src/styles/OrderConfirmListStyle.scss
OrderConfirmPage에서 사용자가 취소하는 것 구현
(#386)
=> feat: 주문 내역 취소 구현, 취소 스타일 구현

src/styles/HeaderStyle.scss, src/styles/HomeStyle.scss, src/styles/NoticeAllStyle.scss
=> refactor: 수정사항 수정

src/pages/HomePage.js, src/styles/HomeStyle.scss
=> feat: 홈페이지 개발자문의

src/pages/HomePage.js, src/pages/OrderConfirmListPage.js, src/pages/OrderConfirmViewPage.js, src/styles/NoticeListStyle.scss
=> refactor: 한글 영문 교체

src/styles/PaperInfoStyle.scss
데스크탑, 태블릿, 모바일에 따라서 배치 변경
(#413)
=> refactor: 종이정보 페이지 각각 사이즈에 맞춰서 배치 수정

src/pages/OrderPage.js, src/styles/OrderStyle.scss
=> 종이정보 페이지 팝업 버튼 위치 조정

src/styles/OrderCategoryStyle.scss
=> refactor: 주문 예약 페이지 패딩, 마진 수정

src/styles/PopUpPaperInfoStyle.scss
=> fix: 색깔 수정

src/pages/OrderCategoryPage.js, src/pages/PaperInfoPage.js, src/styles/HomeStyle.scss, src/styles/OrderCategoryStyle.scss, src/styles/PaperInfoStyle.scss
=> feat: 종이정보 설명 수정

src/styles/PopUpPaperInfoStyle.scss
=> 종이 정보 팝업 디자인 수정

src/pages/PaperInfoPage.js, src/styles/PopUpPaperInfoStyle.scss, src/widgets/PopUpPaperInfo.js
종이정보 팝업 정보 추가 및 PageInfo text 오타 수정 그리고 뒷배경 클릭시 팝업창 닫기 기능 부여
(#430)
=> feat: 종이정보 팝업 정보 추가

src/styles/OrderStyle.scss
주문상세페이지에서 설정 더보기의 화살표 및 셀렉터 사이 간격 수정
(#430)
=> 주문상세 페이지 옵션 디자인 수정

src/pages/HeaderPage.js, src/routes/AppRouter.js, src/routes/RouteName.js
로그인을 요구하는 페이지에 대해 비로그인시 나타내는 에러 페이지 생성 및 해당 페이지 이동 구현을 위한 라우터 추가
(437)
=> feat: 에러페이지 생성

src/pages/ErrorPage.js, src/pages/UpdatePasswordPage.js, src/styles/PopUpWithOneButtonsWidgets.scss
=> 비밀번호 재설정 페이지 팝업 기능 부여

src/pages/PaperInfoPage.js, src/styles/PaperInfoStyle.scss, src/styles/PopUpPaperInfoStyle.scss, src/widgets/PopUpPaperInfo.js
종이에 대한 상세 정보 기입 및 이에 따른 디자인 변경사항에 대한 반영
(#441)
=> 종이에 대한 상세정보 기입

src/pages/SignInPage.js
위 두가지 사항의 체크 박스를 누를시  해당 내용의 팝업 출력 및 동의 버튼을 누른 뒤에는 체크 박스 입력 자유롭게 가능하도록 구현
(#477)
=> feat: 이용약관 및 개인정보처리방침 체크박스 관련

src/styles/UserLeaveStyle.scss
디스플레이 크기 변화에 따라 나타나는 배경 여백 없애기
(#451)
=> fix: 회원탈퇴 페이지 배경 사이즈 변경

src/functions/SignInFunction.js, src/pages/LogInPage.js, src/pages/SignInPage.js
이미지 스테이션 이메일로 회원가입이랑 로그인 가능하게 구현
(#454)
=> refactor: admin 계정은 gmail로 가입 가능하게 구현

src/pages/OrderConfirmViewPage.js, src/styles/OrderConfirmViewStyle.scss, src/styles/OrderStyle.scss
=> feat: 주문내역확인 페이지의 이미지 사이즈 조정

src/functions/OrderConfirmFunction.js, src/functions/OrderFunction.js, src/models/OrderModel.js, src/pages/OrderConfirmListPage.js, src/pages/OrderConfirmViewPage.js, src/pages/OrderPage.js, src/repositories/OrderRepository.js, src/styles/LoadingStyle.scss, src/styles/OrderConfirmListStyle.scss, src/styles/OrderConfirmViewStyle.scss, src/styles/OrderStyle.scss
완료 요청 일시를 사용자가 입력하게 추가
주문 시 각각 카테고리 별 사이즈 추가
담당자와 상담요청 추가
css 수정
=> refactor/#454 (주문 시 사이즈 추가 & 완료요청일시 추가)

src/pages/OrderPage.js, src/styles/NoticeListStyle.scss, src/styles/OrderStyle.scss
- 홈페이지 공지사항 css 수정
- 주문 페이지 사이즈 수정
- 주문 확인 리스트 날짜 추가
=> refactor/#454 (전제적인 css&기능수정)

src/pages/OrderConfirmViewPage.js, src/styles/OrderConfirmListStyle.scss
=> fix: 주문내역 화면 페이지 배경 수정

src/pages/OrderConfirmListPage.js, src/styles/OrderConfirmListStyle.scss
Admin 계정 상태에서의 주문내역 리스트의 주문 중/ 주문완료 필터 토글 버튼 추가
(#468)
=> feat: 주문내역 리스트 토글 추가

src/functions/SignInFunction.js, src/pages/NoticeViewPage.js, src/pages/SignInPage.js, src/styles/EmailAuthenticationStyle.scss, src/styles/EmailCompletedStyle.scss, src/styles/NoticeAllStyle.scss, src/styles/OrderCategoryStyle.scss, src/styles/SignInStyle.scss
회원가입이 안되던 오류 수정& 각 페이지 배경이 덜 보이던 부분 수정
(#470)
=> fix: 회원가입이 안되던 오류 수정 & css 수정

src/pages/HomePage.js, src/pages/NoticeAllPage.js, src/pages/NoticeListPage.js, src/pages/OrderCategoryPage.js, src/pages/OrderConfirmListPage.js, src/routes/AppRouter.js, src/styles/NoticeAllStyle.scss, src/styles/NoticeListStyle.scss, src/styles/OrderConfirmListStyle.scss, src/styles/OrderStyle.scss, src/styles/PopUpWithOneButtonsWidgets.scss
로그인 없이 사용 시 팝업창 띄우기
공지사항 & 주문 사항 없을 때 문구 추가
=> feat/#473 (로그인 없이 이용시 팝업 추가 & 문구추가)
